package quanticscript

import (
	"testing"
)

func TestCodeGenerator_SimpleFunction(t *testing.T) {
	// Create a simple program with an entry function
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "void"},
				Body: &BlockStmt{
					Statements: []Statement{
						&ReturnStmt{},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	// Verify bytecode is not empty
	if len(bytecode) == 0 {
		t.Fatal("Generated bytecode is empty")
	}

	// Verify it starts with CALL (entry wrapper)
	if bytecode[0] != byte(OpCall) {
		t.Errorf("Expected first opcode to be CALL, got %v", Opcode(bytecode[0]))
	}
}

func TestCodeGenerator_ArithmeticExpression(t *testing.T) {
	// Create a program with arithmetic: return 5 + 3;
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "i64"},
				Body: &BlockStmt{
					Statements: []Statement{
						&ReturnStmt{
							Value: &BinaryExpr{
								Left:     &IntLiteral{Value: "5"},
								Operator: TOKEN_PLUS,
								Right:    &IntLiteral{Value: "3"},
							},
						},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	// Verify bytecode contains PUSH, ADD, and RET instructions
	hasAdd := false
	hasRet := false
	for _, b := range bytecode {
		if Opcode(b) == OpAdd {
			hasAdd = true
		}
		if Opcode(b) == OpRet {
			hasRet = true
		}
	}

	if !hasAdd {
		t.Error("Expected ADD instruction in bytecode")
	}
	if !hasRet {
		t.Error("Expected RET instruction in bytecode")
	}
}

func TestCodeGenerator_VariableDeclaration(t *testing.T) {
	// Create a program with variable: let x: i64 = 42;
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "void"},
				Body: &BlockStmt{
					Statements: []Statement{
						&LetStmt{
							Name:  "x",
							Type:  &TypeAnnotation{Name: "i64"},
							Value: &IntLiteral{Value: "42"},
						},
						&ReturnStmt{},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	// Verify bytecode contains STORE instruction
	hasStore := false
	for _, b := range bytecode {
		if Opcode(b) == OpStore {
			hasStore = true
			break
		}
	}

	if !hasStore {
		t.Error("Expected STORE instruction in bytecode")
	}
}

func TestCodeGenerator_InlineAssembly(t *testing.T) {
	// Create a program with inline assembly
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "void"},
				Body: &BlockStmt{
					Statements: []Statement{
						&AsmBlock{
							Instructions: []AsmInstruction{
								{
									Mnemonic: "PUSH",
									Operands: []string{"i64", "100"},
								},
								{
									Mnemonic: "POP",
									Operands: []string{},
								},
							},
						},
						&ReturnStmt{},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	// Verify bytecode contains PUSH and POP instructions
	hasPush := false
	hasPop := false
	for _, b := range bytecode {
		if Opcode(b) == OpPush {
			hasPush = true
		}
		if Opcode(b) == OpPop {
			hasPop = true
		}
	}

	if !hasPush {
		t.Error("Expected PUSH instruction in bytecode")
	}
	if !hasPop {
		t.Error("Expected POP instruction in bytecode")
	}
}

func TestCodeGenerator_NoEntryFunction(t *testing.T) {
	// Create a program without an entry function
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "helper",
				IsExport:   false,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "void"},
				Body: &BlockStmt{
					Statements: []Statement{
						&ReturnStmt{},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	_, err := cg.Generate(program)
	if err == nil {
		t.Fatal("Expected error for missing entry function, got nil")
	}

	expectedMsg := "no exported 'entry' function found"
	if err.Error() != expectedMsg {
		t.Errorf("Expected error message '%s', got '%s'", expectedMsg, err.Error())
	}
}
