package quanticscript

import (
	"testing"
)

// TestCodeGenIntegration_SimpleProgram tests the full pipeline from AST to bytecode
func TestCodeGenIntegration_SimpleProgram(t *testing.T) {
	// Create a simple program: export function entry(): i64 { return 42; }
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "i64"},
				Body: &BlockStmt{
					Statements: []Statement{
						&ReturnStmt{
							Value: &IntLiteral{Value: "42"},
						},
					},
				},
			},
		},
	}

	// Generate bytecode
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	// Create bytecode file with header
	bytecodeFile := CreateBytecode(bytecode, 0)

	// Verify it's valid QuanticScript bytecode
	if !IsQuanticScriptBytecode(bytecodeFile) {
		t.Fatal("Generated bytecode is not valid QuanticScript bytecode")
	}

	// Parse header
	header, err := ParseBytecodeHeader(bytecodeFile)
	if err != nil {
		t.Fatalf("Failed to parse bytecode header: %v", err)
	}

	if header.Magic != BytecodeMagic {
		t.Errorf("Expected magic %x, got %x", BytecodeMagic, header.Magic)
	}

	if header.Version != BytecodeVersion {
		t.Errorf("Expected version %x, got %x", BytecodeVersion, header.Version)
	}

	// Execute the bytecode
	body, err := GetBytecodeBody(bytecodeFile)
	if err != nil {
		t.Fatalf("Failed to get bytecode body: %v", err)
	}

	interpreter := NewBytecodeInterpreter(body, nil, 1000000)
	err = interpreter.Execute()
	if err != nil {
		t.Fatalf("Failed to execute bytecode: %v", err)
	}

	// Get result from stack
	if len(interpreter.stack) == 0 {
		t.Fatal("Expected result on stack")
	}
	result := interpreter.stack[len(interpreter.stack)-1]

	// Verify result
	if result.Type != TypeI64 {
		t.Errorf("Expected result type i64, got %v", result.Type)
	}

	val, err := result.AsI64()
	if err != nil {
		t.Fatalf("Failed to get i64 value: %v", err)
	}

	if val != 42 {
		t.Errorf("Expected result 42, got %d", val)
	}
}

// TestCodeGenIntegration_WithVariables tests code generation with local variables
func TestCodeGenIntegration_WithVariables(t *testing.T) {
	// Create program: export function entry(): i64 { let x: i64 = 10; let y: i64 = 20; return x + y; }
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "i64"},
				Body: &BlockStmt{
					Statements: []Statement{
						&LetStmt{
							Name:  "x",
							Type:  &TypeAnnotation{Name: "i64"},
							Value: &IntLiteral{Value: "10"},
						},
						&LetStmt{
							Name:  "y",
							Type:  &TypeAnnotation{Name: "i64"},
							Value: &IntLiteral{Value: "20"},
						},
						&ReturnStmt{
							Value: &BinaryExpr{
								Left:     &IdentExpr{Name: "x"},
								Operator: TOKEN_PLUS,
								Right:    &IdentExpr{Name: "y"},
							},
						},
					},
				},
			},
		},
	}

	// Generate and execute
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	bytecodeFile := CreateBytecode(bytecode, 0)
	body, _ := GetBytecodeBody(bytecodeFile)

	interpreter := NewBytecodeInterpreter(body, nil, 1000000)
	err = interpreter.Execute()
	if err != nil {
		t.Fatalf("Failed to execute bytecode: %v", err)
	}

	if len(interpreter.stack) == 0 {
		t.Fatal("Expected result on stack")
	}
	result := interpreter.stack[len(interpreter.stack)-1]
	val, _ := result.AsI64()
	if val != 30 {
		t.Errorf("Expected result 30, got %d", val)
	}
}

// TestCodeGenIntegration_InlineAssembly tests inline assembly code generation
func TestCodeGenIntegration_InlineAssembly(t *testing.T) {
	// Create program with inline assembly:
	// export function entry(): i64 {
	//   let result: i64;
	//   __asm__ {
	//     PUSH i64 100
	//     STORE result
	//   }
	//   return result;
	// }
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "i64"},
				Body: &BlockStmt{
					Statements: []Statement{
						&LetStmt{
							Name: "result",
							Type: &TypeAnnotation{Name: "i64"},
						},
						&AsmBlock{
							Instructions: []AsmInstruction{
								{
									Mnemonic: "PUSH",
									Operands: []string{"i64", "100"},
								},
								{
									Mnemonic: "STORE",
									Operands: []string{"result"},
								},
							},
						},
						&ReturnStmt{
							Value: &IdentExpr{Name: "result"},
						},
					},
				},
			},
		},
	}

	// Generate and execute
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	bytecodeFile := CreateBytecode(bytecode, 0)
	body, _ := GetBytecodeBody(bytecodeFile)

	interpreter := NewBytecodeInterpreter(body, nil, 1000000)
	err = interpreter.Execute()
	if err != nil {
		t.Fatalf("Failed to execute bytecode: %v", err)
	}

	if len(interpreter.stack) == 0 {
		t.Fatal("Expected result on stack")
	}
	result := interpreter.stack[len(interpreter.stack)-1]
	val, _ := result.AsI64()
	if val != 100 {
		t.Errorf("Expected result 100, got %d", val)
	}
}

// TestCodeGenIntegration_ControlFlow tests if statement code generation
func TestCodeGenIntegration_ControlFlow(t *testing.T) {
	// Create program: export function entry(): i64 { if (true) { return 1; } else { return 2; } }
	program := &Program{
		Declarations: []Node{
			&FunctionDecl{
				Name:       "entry",
				IsExport:   true,
				Parameters: []*Parameter{},
				ReturnType: &TypeAnnotation{Name: "i64"},
				Body: &BlockStmt{
					Statements: []Statement{
						&IfStmt{
							Condition: &BoolLiteral{Value: true},
							ThenBlock: &BlockStmt{
								Statements: []Statement{
									&ReturnStmt{
										Value: &IntLiteral{Value: "1"},
									},
								},
							},
							ElseBlock: &BlockStmt{
								Statements: []Statement{
									&ReturnStmt{
										Value: &IntLiteral{Value: "2"},
									},
								},
							},
						},
					},
				},
			},
		},
	}

	// Generate and execute
	cg := NewCodeGenerator()
	bytecode, err := cg.Generate(program)
	if err != nil {
		t.Fatalf("Failed to generate bytecode: %v", err)
	}

	bytecodeFile := CreateBytecode(bytecode, 0)
	body, _ := GetBytecodeBody(bytecodeFile)

	interpreter := NewBytecodeInterpreter(body, nil, 1000000)
	err = interpreter.Execute()
	if err != nil {
		t.Fatalf("Failed to execute bytecode: %v", err)
	}

	if len(interpreter.stack) == 0 {
		t.Fatal("Expected result on stack")
	}
	result := interpreter.stack[len(interpreter.stack)-1]
	val, _ := result.AsI64()
	if val != 1 {
		t.Errorf("Expected result 1 (then branch), got %d", val)
	}
}
