package quanticscript

import (
	"encoding/binary"
	"testing"
)

// TestStakingProgramCompilation tests that the staking program compiles successfully
func TestStakingProgramCompilation(t *testing.T) {
	t.Run("StakingProgram_Compiles", func(t *testing.T) {
		// Minimal staking program for testing
		source := `
export function entry(): i64 {
    let instrData: bytes = getInstructionData();
    if (len(instrData) < 8) {
        return 0x3FFF;
    }
    let typeBytes: bytes = slice(instrData, 0, 8);
    let instrType: i64 = bytesToI64LE(typeBytes);
    instrType = instrType & 255;
    return 0;
}
`

		lexer := NewLexer(source, "staking.qs")
		parser := NewParser(lexer)
		program := parser.ParseProgram()

		checkParserErrors(t, parser)

		if len(program.Declarations) != 1 {
			t.Fatalf("expected 1 declaration, got %d", len(program.Declarations))
		}

		typeChecker := NewTypeChecker()
		typeChecker.CheckProgram(program)

		if len(typeChecker.Errors()) > 0 {
			t.Fatalf("Type checker errors: %v", typeChecker.Errors())
		}

		codeGen := NewCodeGenerator()
		bytecode, err := codeGen.Generate(program)

		if err != nil {
			t.Fatalf("Code generator error: %v", err)
		}

		if len(bytecode) == 0 {
			t.Fatal("Generated bytecode is empty")
		}
	})
}

// TestStakingProgramInstructionDispatch tests instruction dispatch logic
func TestStakingProgramInstructionDispatch(t *testing.T) {
	t.Run("RegisterValidator_InstructionType", func(t *testing.T) {
		// Create instruction data: [type:u8][pubkey:32][commission:i64]
		pubkey := make([]byte, 32)
		for i := range pubkey {
			pubkey[i] = byte(i)
		}

		instrData := make([]byte, 41)
		instrData[0] = 0 // INSTR_REGISTER_VALIDATOR
		copy(instrData[1:33], pubkey)
		binary.LittleEndian.PutUint64(instrData[33:41], 10) // commission = 10%

		// Verify instruction data format
		if len(instrData) != 41 {
			t.Errorf("expected instruction data length 41, got %d", len(instrData))
		}

		// Verify instruction type extraction
		typeBytes := instrData[0:8]
		instrType := int64(typeBytes[0])
		if instrType != 0 {
			t.Errorf("expected instruction type 0, got %d", instrType)
		}
	})

	t.Run("DelegateStake_InstructionType", func(t *testing.T) {
		// Create instruction data: [type:u8][validatorFileID:32][amount:i64]
		validatorFileID := make([]byte, 32)
		for i := range validatorFileID {
			validatorFileID[i] = byte(i)
		}

		instrData := make([]byte, 41)
		instrData[0] = 2 // INSTR_DELEGATE_STAKE
		copy(instrData[1:33], validatorFileID)
		binary.LittleEndian.PutUint64(instrData[33:41], 1000000) // amount = 1 Neon

		// Verify instruction data format
		if len(instrData) != 41 {
			t.Errorf("expected instruction data length 41, got %d", len(instrData))
		}

		// Verify instruction type extraction
		typeBytes := instrData[0:8]
		instrType := int64(typeBytes[0])
		if instrType != 2 {
			t.Errorf("expected instruction type 2, got %d", instrType)
		}
	})

	t.Run("DistributeRewards_InstructionType", func(t *testing.T) {
		// Create instruction data: [type:u8][rewardAmount:i64][totalBlocksProduced:i64]
		instrData := make([]byte, 17)
		instrData[0] = 5                                       // INSTR_DISTRIBUTE_REWARDS
		binary.LittleEndian.PutUint64(instrData[1:9], 1000000) // rewardAmount = 1 Neon
		binary.LittleEndian.PutUint64(instrData[9:17], 100)    // totalBlocksProduced = 100

		// Verify instruction data format
		if len(instrData) != 17 {
			t.Errorf("expected instruction data length 17, got %d", len(instrData))
		}

		// Verify instruction type extraction
		typeBytes := instrData[0:8]
		instrType := int64(typeBytes[0])
		if instrType != 5 {
			t.Errorf("expected instruction type 5, got %d", instrType)
		}
	})

	t.Run("ReportDoubleSign_InstructionType", func(t *testing.T) {
		// Create instruction data: [type:u8][validatorPubkey:32][blockHash1:32][blockHash2:32][sig1:64][sig2:64]
		instrData := make([]byte, 225)
		instrData[0] = 6 // INSTR_REPORT_DOUBLE_SIGN

		// Verify instruction data format
		if len(instrData) != 225 {
			t.Errorf("expected instruction data length 225, got %d", len(instrData))
		}

		// Verify instruction type extraction
		typeBytes := instrData[0:8]
		instrType := int64(typeBytes[0])
		if instrType != 6 {
			t.Errorf("expected instruction type 6, got %d", instrType)
		}
	})
}
