#!/usr/bin/env bash

# Script to run Fibonacci example with dynamic input
# Usage: ./run_fibonacci.sh <n>

if [ $# -eq 0 ]; then
    echo "Usage: $0 <n>"
    echo "Example: $0 10"
    exit 1
fi

N=$1

# Validate input is a number
if ! [[ "$N" =~ ^[0-9]+$ ]]; then
    echo "Error: Input must be a positive integer"
    exit 1
fi

echo "Computing fibonacci($N)..."
echo ""

# Create temporary QuanticScript file with the specified n
cat > /tmp/fibonacci_temp.qs << EOF
// Temporary Fibonacci example with n=$N

function fibonacci(n: i64): i64 {
    if (n <= 0) {
        return 0;
    }
    if (n == 1) {
        return 1;
    }
    return fibonacci(n - 1) + fibonacci(n - 2);
}

export function entry(): i64 {
    return fibonacci($N);
}
EOF

# Compile the temporary file
echo "Compiling..."
go run cmd/main.go qsc compile -i /tmp/fibonacci_temp.qs -o /tmp/fibonacci_temp.qsb

if [ $? -ne 0 ]; then
    echo "Compilation failed!"
    rm -f /tmp/fibonacci_temp.qs /tmp/fibonacci_temp.qsb
    exit 1
fi

echo ""
echo "Disassembling to show generated bytecode..."
go run cmd/main.go qsc disassemble -i /tmp/fibonacci_temp.qsb -o /tmp/fibonacci_temp.qsa

echo ""
echo "Assembly output (first 30 lines):"
echo "----------------------------------------"
head -30 /tmp/fibonacci_temp.qsa
echo "----------------------------------------"

echo ""
echo "Running interpreter..."

# Create a temporary test that will run our bytecode
cat > internal/quanticscript/temp_fib_test.go << 'GOEOF'
package quanticscript

import (
	"fmt"
	"os"
	"testing"
)

func TestTempFibonacci(t *testing.T) {
	bytecode, err := os.ReadFile("/tmp/fibonacci_temp.qsb")
	if err != nil {
		t.Fatalf("Failed to read bytecode: %v", err)
	}

	body, err := GetBytecodeBody(bytecode)
	if err != nil {
		t.Fatalf("Failed to extract bytecode body: %v", err)
	}

	ctx := NewMockExecutionContext()
	interpreter := NewBytecodeInterpreter(body, ctx, 100000000)

	err = interpreter.Execute()
	if err != nil {
		t.Fatalf("Execution failed: %v", err)
	}

	if len(interpreter.stack) != 1 {
		t.Fatalf("Expected 1 value on stack, got %d", len(interpreter.stack))
	}

	result, err := interpreter.stack[0].AsI64()
	if err != nil {
		t.Fatalf("Failed to get i64 result: %v", err)
	}

	fmt.Printf("\n✓ Result: fibonacci(%s) = %d\n\n", os.Getenv("FIB_N"), result)
}
GOEOF

# Run the test
FIB_N=$N go test -count=1 -v ./internal/quanticscript -run TestTempFibonacci

# Cleanup
rm -f /tmp/fibonacci_temp.qs /tmp/fibonacci_temp.qsb /tmp/fibonacci_temp.qsa internal/quanticscript/temp_fib_test.go

echo "Done!"
